version: "3.2"

services:
  # PSX Conversion from bin/cue to chd
  convert_psx:
    build:
      context: .
      dockerfile: Dockerfile_PSX
    image: dafrenchyman/emucleaning_psx
    command: /app/convert_psx.sh
    volumes:
      - "./PSX/zip:/app/zip"
      - "./PSX/chd:/app/chd"
