#!/bin/bash
# Helper method to create symbolic links for all the folders I have everywhere

ln -s "/mnt/Bank/SnapArrays/SsdArray01/SnapDisk_4TB_25/Consoles/.artwork/" "/ROMs/.assets"
ln -s "/mnt/Bank/SnapArrays/SsdArray01/SnapDisk_4TB_27/Consoles/Bioses/" "/bioses" 
ln -s "/mnt/Bank/SnapArrays/SsdArray02/Snap2_SSD_8TB_04/Consoles/Panasonic - 3DO/" "/ROMs/3do" 
ln -s "/mnt/Bank/SnapArrays/SsdArray02/Snap2_SSD_8TB_04/Consoles/Commodore - Amiga/" "/ROMs/amiga" 
ln -s "/mnt/Bank/SnapArrays/SsdArray02/Snap2_SSD_8TB_02/Consoles/Amiga - CD32/" "/ROMs/amigacd32" 
ln -s "/mnt/Bank/SnapArrays/SsdArray01/SnapDisk_4TB_27/Consoles/Arcade/" "/ROMs/arcade" 
ln -s "/mnt/Bank/SnapArrays/SsdArray01/SnapDisk_4TB_27/Consoles/Atari - 2600/" "/ROMs/atari2600" 
ln -s "/mnt/Bank/SnapArrays/SsdArray02/Snap2_SSD_8TB_04/Consoles/Atari - 5200/" "/ROMs/atari5200" 
ln -s "/mnt/Bank/SnapArrays/SsdArray02/Snap2_SSD_8TB_04/Consoles/Atari - 7800/" "/ROMs/atari7800" 
ln -s "/mnt/Bank/SnapArrays/SsdArray02/Snap2_SSD_8TB_04/Consoles/Atari - Jaguar/" "/ROMs/atarijaguar" 
ln -s "/mnt/Bank/SnapArrays/SsdArray02/Snap2_SSD_8TB_02/Consoles/Atari - Jaguar CD/" "/ROMs/atarijaguarcd" 
ln -s "/mnt/Bank/SnapArrays/SsdArray02/Snap2_SSD_8TB_04/Consoles/Atari - Lynx/" "/ROMs/atarilynx" 
ln -s "/mnt/Bank/SnapArrays/SsdArray02/Snap2_SSD_8TB_04/Consoles/Atari - ST/" "/ROMs/atarist" 
ln -s "/mnt/Bank/SnapArrays/SsdArray02/Snap2_SSD_8TB_04/Consoles/Coleco - ColecoVision/" "/ROMs/colecovision" 
ln -s "/mnt/Bank/SnapArrays/SsdArray02/Snap2_SSD_8TB_04/Consoles/Sega - Dreamcast/" "/ROMs/dreamcast" 
ln -s "/mnt/Bank/SnapArrays/SsdArray01/SnapDisk_4TB_27/Consoles/Nintendo - Game Boy/Games/" "/ROMs/gb"
ln -s "/mnt/Bank/SnapArrays/SsdArray01/SnapDisk_4TB_27/Consoles/Nintendo - Game Boy Color/Games/" "/ROMs/gbc"
ln -s "/mnt/Bank/SnapArrays/SsdArray01/SnapDisk_4TB_27/Consoles/Nintendo - Game Boy Advance/" "/ROMs/gba"
ln -s "/mnt/Bank/SnapArrays/SsdArray01/SnapDisk_4TB_27/Consoles/Nintendo - Gamecube/" "/ROMs/gc" 
ln -s "/mnt/Bank/SnapArrays/SsdArray01/SnapDisk_4TB_27/Consoles/Sega - Mega Drive - Genesis/Games/" "/ROMs/genesis"
ln -s "/mnt/Bank/SnapArrays/SsdArray02/Snap2_SSD_8TB_04/Consoles/Sega - Mega CD/" "/ROMs/megacd"
ln -s "/mnt/Bank/SnapArrays/SsdArray01/SnapDisk_4TB_27/Consoles/Sega - Model 2/" "/ROMs/model2"
ln -s "/mnt/Bank/SnapArrays/SsdArray01/SnapDisk_4TB_27/Consoles/Sega - Model 3/" "/ROMs/model3"
ln -s "/mnt/Bank/SnapArrays/SsdArray01/SnapDisk_4TB_27/Consoles/Sega - Naomi/" "/ROMs/naomi"
ln -s "/mnt/Bank/SnapArrays/SsdArray02/Snap2_SSD_8TB_04/Consoles/SNK - Neo Geo/" "/ROMs/neogeo" 
ln -s "/mnt/Bank/SnapArrays/SsdArray01/SnapDisk_4TB_27/Consoles/Nintendo - Nintendo Entertainment System/Games/" "/ROMs/nes"
ln -s "/mnt/Bank/SnapArrays/SsdArray01/SnapDisk_4TB_27/Consoles/SNK - NeoGeo Pocket/" "/ROMs/ngp" 
ln -s "/mnt/Bank/SnapArrays/SsdArray01/SnapDisk_4TB_27/Consoles/SNK - NeoGeo Pocket Color/" "/ROMs/ngpc" 
ln -s "/mnt/Bank/SnapArrays/SsdArray02/Snap2_SSD_8TB_02/Consoles/NEC - PC Engine CD/" "/ROMs/pcenginecd" 
ln -s "/mnt/Bank/SnapArrays/SsdArray02/Snap2_SSD_8TB_04/Consoles/Sony - Playstation 2/" "/ROMs/ps2"
# ln -s "/mnt/Bank/SnapArrays/SsdArray02/Snap2_SSD_8TB_02/Consoles/Sony - Playstation 3/" "/ROMs/ps3"
ln -s "/mnt/Bank/SnapArrays/pool/pool/Consoles/Sony - Playstation 3/Games/" "/ROMs/ps3"
ln -s "/mnt/Bank/SnapArrays/SsdArray02/Snap2_SSD_8TB_02/Consoles/Sony - Playstation Portable/" "/ROMs/psp"
ln -s "/mnt/Bank/SnapArrays/SsdArray01/SnapDisk_4TB_27/Consoles/Sony - Play Station Vita/" "/ROMs/psvita" 
ln -s "/mnt/Bank/SnapArrays/SsdArray01/SnapDisk_4TB_24/Consoles/Sony - Playstation (USA)/" "/ROMs/psx"
ln -s "/mnt/Bank/SnapArrays/SsdArray02/Snap2_SSD_8TB_04/Consoles/Casio - PV-1000/" "/ROMs/pv1000" 
ln -s "/mnt/Bank/SnapArrays/SsdArray02/Snap2_SSD_8TB_02/Consoles/Sega - Saturn/" "/ROMs/saturn"
ln -s "/mnt/Bank/SnapArrays/SsdArray01/SnapDisk_4TB_01/Consoles/Scumm/" "/ROMs/scummvm"
ln -s "/mnt/Bank/SnapArrays/SsdArray01/SnapDisk_4TB_27/Consoles/Sega - 32X/Games/" "/ROMs/sega32x"
ln -s "/mnt/Bank/SnapArrays/SsdArray02/Snap2_SSD_8TB_04/Consoles/Sega - Sega CD/" "/ROMs/segacd"
ln -s "/mnt/Bank/SnapArrays/SsdArray01/SnapDisk_4TB_25/Consoles/Nintendo - Super Nintendo/Games/" "/ROMs/snes"
ln -s "/mnt/Bank/SnapArrays/SsdArray02/Snap2_SSD_8TB_04/Consoles/Nintendo - SNES Widescreen/" "/ROMs/snes_widescreen" 
ln -s "/mnt/Bank/SnapArrays/SsdArray02/Snap2_SSD_8TB_04/Consoles/Nintendo - Switch/Games/" "/ROMs/switch" 
ln -s "/mnt/Bank/SnapArrays/SsdArray02/Snap2_SSD_8TB_02/Consoles/NEC - Turbo Grafx CD/" "/ROMs/tg-cd" 
ln -s "/mnt/Bank/SnapArrays/SsdArray02/Snap2_SSD_8TB_04/Consoles/Bandai - WonderSwan/" "/ROMs/wonderswan" 
ln -s "/mnt/Bank/SnapArrays/SsdArray02/Snap2_SSD_8TB_04/Consoles/Bandai - WonderSwan Color/" "/ROMs/wonderswancolor" 
ln -s "/mnt/Bank/SnapArrays/SsdArray01/SnapDisk_4TB_02/Consoles/Nintendo - Wii/" "/ROMs/wii" 
ln -s "/mnt/Bank/SnapArrays/SsdArray01/SnapDisk_4TB_27/Consoles/Nintendo - WiiU/Games/" "/ROMs/wiiu"
ln -s "/mnt/Bank/SnapArrays/SsdArray01/SnapDisk_4TB_13/Consoles/Microsoft - Xbox/Games - Processed/" "/ROMs/xbox" 
ln -s "/mnt/Bank/SnapArrays/SsdArray02/Snap2_SSD_8TB_04/Consoles/Nintendo 64/" "/ROMs/n64" 
ln -s "/mnt/Bank/SnapArrays/SsdArray02/Snap2_SSD_8TB_04/Consoles/Nintendo - Virtual Boy/" "/ROMs/virtualboy" 
ln -s "/mnt/Bank/SnapArrays/SsdArray02/Snap2_SSD_8TB_07/Consoles/Nintendo - Gamecube/TexturePacks" "/home/retro/.local/share/dolphin-emu/Load/Textures"